#!/usr/bin/php
<?php
/**
 * Yuju command line File
 *
 * @category CLI
 * @package  YujuFramework
 * @author   Daniel Fernández <daniel.fdez.fdez@gmail.com>
 * @license  http://www.gnu.org/copyleft/lesser.html  LGPL License 2.1
 * @link     https://github.com/yuju-framework/yuju
 * @since    version 1.0
 */

require 'lib/autoload.php';
require 'lib/common.php';

if (count($argv)<2) {
    showHelp();
    exit;
}

require 'lib/downloadlibs.php';
switch ($argv[1]) {
    case 'create':
        include 'lib/create.php';
        create();
        break;
    case 'delete':
        include 'lib/delete.php';
        delete($argv[2]);
        break;
    case 'compile':
        include 'lib/compile.php';
        compile($argv[2], $argv[3]);
        break;
    case 'install':
        include 'lib/packages.php';
        install($argv[2]);
        break;
    case 'orm':
        include 'lib/orm.php';
        if (count($argv)<5) {
            showHelp();
            exit;
        }
        if (isset($argv[6])) {
            $name = $argv[6];
        } else {
            $name = null;
        }
        orm($argv[2], $argv[3], $argv[4], $argv[5], $name);
        break;
    default:
        showHelp();
        exit;
        break;
}
